#include "../utilities/template.h"

// The header takes `mod` and `modpow` from ModPow.h. Shadow them with a
// run-time modulus so that several prime moduli can be tested in one binary.
ll mod = 5;
ll modpow(ll a, ll e) {
	ll r = 1;
	for (a %= mod; e; e >>= 1, a = a * a % mod) if (e & 1) r = r * a % mod;
	return r;
}

#define mod dummy
#define modpow dummy2
#include "../../content/number-theory/ModPow.h"
#undef mod
#undef modpow

#include "../../content/numerical/BerlekampMassey.h"

template<class F>
void gen(vector<ll>& v, int at, F f) {
	if (at == sz(v)) f();
	else {
		rep(i,0,mod) {
			v[at] = i;
			gen(v, at+1, f);
		}
	}
}

// Oracle: is there a recurrence of order L, s[i] = sum_j c[j] * s[i-1-j] for
// all L <= i < n? Decided by Gaussian elimination mod p.
bool hasOrder(const vector<ll>& s, int L) {
	int n = sz(s), rows = n - L;
	if (rows <= 0) return true;
	vector<vector<ll>> A(rows, vector<ll>(L + 1));
	rep(i,L,n) {
		rep(j,0,L) A[i-L][j] = s[i-1-j];
		A[i-L][L] = s[i];
	}
	int r = 0;
	rep(c,0,L) {
		int p = -1;
		rep(i,r,rows) if (A[i][c]) { p = i; break; }
		if (p == -1) continue;
		swap(A[p], A[r]);
		ll inv = modpow(A[r][c], mod - 2);
		rep(k,c,L+1) A[r][k] = A[r][k] * inv % mod;
		rep(i,0,rows) if (i != r && A[i][c]) {
			ll v = A[i][c];
			rep(k,c,L+1) A[i][k] = ((A[i][k] - v * A[r][k]) % mod + mod) % mod;
		}
		r++;
	}
	rep(i,r,rows) if (A[i][L]) return false;
	return true;
}
int minOrder(const vector<ll>& s) {
	rep(L,0,sz(s)+1) if (hasOrder(s, L)) return L;
	assert(0); return -1;
}

// s must have values in [0, mod)
void check(const vector<ll>& s) {
	vector<ll> c = berlekampMassey(s);
	int L = sz(c), n = sz(s);
	for (ll x : c) assert(0 <= x && x < mod);
	rep(i,L,n) {
		ll x = 0;
		rep(j,0,L) x = (x + c[j] * s[i-1-j]) % mod;
		assert(x == s[i]);
	}
	assert(L == minOrder(s));
}

mt19937_64 rng(12345);
ll rnd(ll lo, ll hi) { return lo + (ll)(rng() % (unsigned long long)(hi - lo + 1)); }

int main() {
	// Original test: sequences generated by an order-n recurrence, mod 5.
	mod = 5;
	rep(n,1,5) {
		vector<ll> start(n);
		vector<ll> coef(n), coef2;
		vector<ll> full(2*n);
		gen(start, 0, [&]() {
		gen(coef, 0, [&]() {
			rep(i,0,n) full[i] = start[i];
			rep(i,n,2*n) full[i] = 0;
			rep(i,n,2*n) rep(j,0,n) full[i] = (full[i] + coef[j] * full[i-1 - j]) % mod;
			coef2 = berlekampMassey(full);
			if (sz(coef2) == n) assert(coef == coef2);
			rep(i,n,2*n) {
				ll x = 0;
				rep(j,0,sz(coef2)) x = (x + coef2[j] * full[i-1 - j]) % mod;
				assert(x == full[i]);
			}
		});
		});
	}

	// Usage example from the header.
	mod = 1000000007;
	assert((berlekampMassey({0, 1, 1, 3, 5, 11}) == vector<ll>{1, 2}));

	// Exhaustive over ALL sequences (not only recurrent ones) of short
	// length: the result must be a valid recurrence of minimal order.
	for (auto [p, maxn] : vector<pii>{{2, 13}, {3, 8}, {5, 6}, {7, 5}}) {
		mod = p;
		rep(n,1,maxn+1) {
			vector<ll> s(n);
			gen(s, 0, [&]() { check(s); });
		}
	}

	// Random sequences for big and small primes: fully random, generated
	// by a low order recurrence, and a recurrent prefix with a broken tail.
	for (ll p : {2LL, 3LL, 5LL, 998244353LL, 1000000007LL, 2147483647LL}) {
		mod = p;
		rep(it,0,1500) {
			int n = (int)rnd(1, 40);
			vector<ll> s(n);
			int type = (int)rnd(0, 2);
			if (type == 0) for (ll& x : s) x = rnd(0, mod - 1);
			else {
				int k = (int)rnd(0, n / 2);
				vector<ll> c(k);
				for (ll& x : c) x = rnd(0, mod - 1);
				rep(i,0,n) {
					if (i < k) s[i] = rnd(0, mod - 1);
					else rep(j,0,k) s[i] = (s[i] + c[j] * s[i-1-j]) % mod;
				}
				if (type == 2) rep(i,(int)rnd(0, n-1),n) s[i] = rnd(0, mod - 1);
			}
			// 2n terms of an order <= n recurrence give order <= n.
			if (type == 1) assert(sz(berlekampMassey(s)) <= n / 2);
			if (rnd(0, 9) == 0) rep(i,0,(int)rnd(0, n)) s[i] = 0; // leading zeros
			check(s);
		}
	}

	// Values outside [0, mod) (negative, or >= mod) give the same answer.
	for (ll p : {5LL, 1000000007LL}) {
		mod = p;
		rep(it,0,2000) {
			int n = (int)rnd(1, 20);
			vector<ll> s(n), t;
			for (ll& x : s) x = rnd(0, mod - 1);
			t = s;
			for (ll& x : t) x += rnd(-3, 3) * mod;
			assert(berlekampMassey(s) == berlekampMassey(t));
		}
	}

	// An empty sequence has the empty recurrence.
	mod = 1000000007;
	assert(berlekampMassey({}).empty());
	cout<<"Tests passed!"<<endl;
	return 0;
}
